In [2]:
import numpy as np

ages_list = [10, 5, 8, 32, 65, 43]
print(ages_list)



[10, 5, 8, 32, 65, 43]


In [3]:
ages = np.array(ages_list)
print(type(ages))
print(ages)

<class 'numpy.ndarray'>
[10  5  8 32 65 43]


In [4]:
print(ages)
print("Size:\t" , ages.size)
print("Shape:\t", ages.shape)

[10  5  8 32 65 43]
Size:	 6
Shape:	 (6,)


In [5]:
zeroArr = np.zeros(5)
print(zeroArr)

[0. 0. 0. 0. 0.]


In [6]:
weight_list = [32, 18, 26, 60, 55, 65]

In [7]:
people = np.array([ages_list, weight_list])

print("People:\t" , people)
print("Size:\t" , people.size)
print("Shape:\t", people.shape)

People:	 [[10  5  8 32 65 43]
 [32 18 26 60 55 65]]
Size:	 12
Shape:	 (2, 6)


### Exercise

* Generate a 1D numpy array with the values [7, 9, 65, 33, 85, 99]

* Generate a matrix (2D numpy array) of the values:

\begin{align}
  \mathbf{A} =
  \begin{pmatrix}
    1 & 2 & 4 \\
    2 & 3 & 0 \\
    0 & 5 & 1
  \end{pmatrix}
\end{align}

* Change the dimensions of this array to another permitted shape

    

In [9]:
oned_numpy =np.array([7, 9, 65, 33, 85, 99])

In [10]:
oned_numpy

array([ 7,  9, 65, 33, 85, 99])

In [12]:
oned_numpy.size

6

In [19]:
my_mat=[[1,2,4],[2,3,0],[0,5,1]]
my_mat=np.array(my_mat)
my_mat

array([[1, 2, 4],
       [2, 3, 0],
       [0, 5, 1]])

In [20]:
my_mat.shape

(3, 3)

In [25]:
my_mat.reshape(9,1)

array([[1],
       [2],
       [4],
       [2],
       [3],
       [0],
       [0],
       [5],
       [1]])

In [26]:
my_mat.reshape(1,9)

array([[1, 2, 4, 2, 3, 0, 0, 5, 1]])

## Array Generation

In [27]:
five_times_table = np.arange(0, 55, 5)
five_times_table

array([ 0,  5, 10, 15, 20, 25, 30, 35, 40, 45, 50])

In [28]:
five_spaced = np.linspace(0,50,11)
print(five_spaced)

[ 0.  5. 10. 15. 20. 25. 30. 35. 40. 45. 50.]


In [29]:
twoArr = np.repeat(2, 10)
print(twoArr)

[2 2 2 2 2 2 2 2 2 2]


In [30]:
identity_matrix = np.eye(6)
print(identity_matrix)

[[1. 0. 0. 0. 0. 0.]
 [0. 1. 0. 0. 0. 0.]
 [0. 0. 1. 0. 0. 0.]
 [0. 0. 0. 1. 0. 0.]
 [0. 0. 0. 0. 1. 0.]
 [0. 0. 0. 0. 0. 1.]]


# Operations

In [31]:
five_times_table


array([ 0,  5, 10, 15, 20, 25, 30, 35, 40, 45, 50])

*italicized text*### Speed Test

In [32]:
fives_list = list(range(0,5001,5))
fives_list

[0,
 5,
 10,
 15,
 20,
 25,
 30,
 35,
 40,
 45,
 50,
 55,
 60,
 65,
 70,
 75,
 80,
 85,
 90,
 95,
 100,
 105,
 110,
 115,
 120,
 125,
 130,
 135,
 140,
 145,
 150,
 155,
 160,
 165,
 170,
 175,
 180,
 185,
 190,
 195,
 200,
 205,
 210,
 215,
 220,
 225,
 230,
 235,
 240,
 245,
 250,
 255,
 260,
 265,
 270,
 275,
 280,
 285,
 290,
 295,
 300,
 305,
 310,
 315,
 320,
 325,
 330,
 335,
 340,
 345,
 350,
 355,
 360,
 365,
 370,
 375,
 380,
 385,
 390,
 395,
 400,
 405,
 410,
 415,
 420,
 425,
 430,
 435,
 440,
 445,
 450,
 455,
 460,
 465,
 470,
 475,
 480,
 485,
 490,
 495,
 500,
 505,
 510,
 515,
 520,
 525,
 530,
 535,
 540,
 545,
 550,
 555,
 560,
 565,
 570,
 575,
 580,
 585,
 590,
 595,
 600,
 605,
 610,
 615,
 620,
 625,
 630,
 635,
 640,
 645,
 650,
 655,
 660,
 665,
 670,
 675,
 680,
 685,
 690,
 695,
 700,
 705,
 710,
 715,
 720,
 725,
 730,
 735,
 740,
 745,
 750,
 755,
 760,
 765,
 770,
 775,
 780,
 785,
 790,
 795,
 800,
 805,
 810,
 815,
 820,
 825,
 830,
 835,
 840,
 845,
 8

In [33]:
five_times_table_lge = np.arange(0,5001,5)
five_times_table_lge

array([   0,    5,   10, ..., 4990, 4995, 5000])

In [34]:
%timeit five_times_table_lge + 5

3.08 µs ± 270 ns per loop (mean ± std. dev. of 7 runs, 100,000 loops each)


In [35]:
%timeit [e + 5 for e in fives_list]

128 µs ± 6.78 µs per loop (mean ± std. dev. of 7 runs, 10,000 loops each)


In [36]:
words = np.array(["ten", "nine", "eight", "seven", "six"])

print(np.isin(words, 'e'))

print("e" in words)
["e" in word for word in words]

[False False False False False]
False


[True, True, True, True, False]

# Transpose

In [37]:
people.shape = (2, 6)
print(people, "\n")
print(people.T)

[[10  5  8 32 65 43]
 [32 18 26 60 55 65]] 

[[10 32]
 [ 5 18]
 [ 8 26]
 [32 60]
 [65 55]
 [43 65]]


# Data Types

In [38]:
people.dtype

dtype('int32')

In [39]:
ages_with_strings = np.array([10, 5, 8, '32', '65', '43'], dtype='int32')
ages_with_strings

array([10,  5,  8, 32, 65, 43])

In [40]:
ages_with_strings = np.array([10, 5, 8, '32', '65', '43'])
print(ages_with_strings)

['10' '5' '8' '32' '65' '43']


In [41]:
ages_with_strings.dtype = 'int32'
print(ages_with_strings)

[49 48  0  0  0  0  0  0  0  0  0 53  0  0  0  0  0  0  0  0  0  0 56  0
  0  0  0  0  0  0  0  0  0 51 50  0  0  0  0  0  0  0  0  0 54 53  0  0
  0  0  0  0  0  0  0 52 51  0  0  0  0  0  0  0  0  0]


In [42]:
ages_with_strings.size

66

In [43]:
ages_with_strings.size/21

3.142857142857143

In [44]:
np.array([10, 5, 8, '32', '65', '43']).size

6

In [45]:
ages_with_strings = np.array([10, 5, 8, '32', '65', '43'])
print(ages_with_strings)
print(ages_with_strings.astype('int32'))

['10' '5' '8' '32' '65' '43']
[10  5  8 32 65 43]


### Exercise

* #### Create an array of string numbers, but use dtype to make it an array of floats.
* #### Transpose the matrix, printing the new size and shape.
* #### Use the .astype() method to convert the array to boolean.

In [52]:
string_num =np.array(['7','9', '65', '33', '85', '99'])

In [53]:
string_num

array(['7', '9', '65', '33', '85', '99'], dtype='<U2')

In [54]:
string_num.dtype

dtype('<U2')

In [69]:
string_num.dtype='float64'

In [70]:
string_num.dtype

dtype('float64')

In [63]:
my_mat1=np.array([[1,2,4],[2,3,0]])
my_mat1

array([[1, 2, 4],
       [2, 3, 0]])

In [65]:
my_mat1.shape

(2, 3)

In [66]:
TRAN_MAT=my_mat1.T

In [67]:
TRAN_MAT

array([[1, 2],
       [2, 3],
       [4, 0]])

In [68]:
TRAN_MAT.shape

(3, 2)

In [73]:
boo=my_mat1.astype(bool)

In [74]:
boo

array([[ True,  True,  True],
       [ True,  True, False]])

In [75]:
boo.dtype

dtype('bool')

## Array Slicing Operations

In [76]:
five_times_table

array([ 0,  5, 10, 15, 20, 25, 30, 35, 40, 45, 50])

In [77]:
five_times_table[0]

0

In [78]:
five_times_table[-1]

50

In [79]:
five_times_table[:4]

array([ 0,  5, 10, 15])

In [80]:
five_times_table[4:]

array([20, 25, 30, 35, 40, 45, 50])

In [81]:
print(people)
people[:3, :3]

[[10  5  8 32 65 43]
 [32 18 26 60 55 65]]


array([[10,  5,  8],
       [32, 18, 26]])

### Exercise

* Create a numpy array with 50 zeros
* Create a np array of 2 repeated 20 times
* Create a numpy array from 0 to 2 $\pi$ in steps of 0.1

For one of the arrays generated:
* Get the first five values
* Get the last 3 values
* Get the 4th value to the 7th value

In [82]:
zero=np.zeros(50)

In [83]:
zero

array([0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
       0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
       0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.])

In [84]:
two=np.repeat(2, 20)

In [85]:
two

array([2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2])

In [89]:
import math
pi=np.arange(0, math.pi, 0.1)

In [90]:
pi

array([0. , 0.1, 0.2, 0.3, 0.4, 0.5, 0.6, 0.7, 0.8, 0.9, 1. , 1.1, 1.2,
       1.3, 1.4, 1.5, 1.6, 1.7, 1.8, 1.9, 2. , 2.1, 2.2, 2.3, 2.4, 2.5,
       2.6, 2.7, 2.8, 2.9, 3. , 3.1])

In [93]:
pi[0:5]

array([0. , 0.1, 0.2, 0.3, 0.4])

In [96]:
pi[-3:]

array([2.9, 3. , 3.1])

In [99]:
pi[3:7]

array([0.3, 0.4, 0.5, 0.6])

In [100]:
reverse_five_times_table = np.flip(five_times_table)
reverse_five_times_table

array([50, 45, 40, 35, 30, 25, 20, 15, 10,  5,  0])

In [101]:
reverse_five_times_table = five_times_table[-1::-1]
print(reverse_five_times_table)
five_times_table

[50 45 40 35 30 25 20 15 10  5  0]


array([ 0,  5, 10, 15, 20, 25, 30, 35, 40, 45, 50])

In [102]:
five_times_table[0::3] #Every 3rd element starting from 0

array([ 0, 15, 30, 45])

### Exercise
Take one of the arrays you defined and
* #### Reverse it
* #### Only keep every 4th element.
* #### Get every 2nd element, starting from the last and moving backwards.

In [97]:
reverse_l = np.flip(pi)

In [98]:
reverse_l

array([3.1, 3. , 2.9, 2.8, 2.7, 2.6, 2.5, 2.4, 2.3, 2.2, 2.1, 2. , 1.9,
       1.8, 1.7, 1.6, 1.5, 1.4, 1.3, 1.2, 1.1, 1. , 0.9, 0.8, 0.7, 0.6,
       0.5, 0.4, 0.3, 0.2, 0.1, 0. ])

In [103]:
reverse_l[0::4]

array([3.1, 2.7, 2.3, 1.9, 1.5, 1.1, 0.7, 0.3])

# Stats

In [104]:
np.array([1.65432, 5.98765]).round(2)

array([1.65, 5.99])

In [105]:
nums = np.arange(0, 4, 0.2555)

### Exercise

* Compute min, max, sum, mean, median, variance, and standard deviation of the above array, all to to 2 decimal places.

In [107]:
print("min = ", np.min(nums).round(2))
print("max = ", np.max(nums).round(2))
print("sum = ", np.sum(nums).round(2))
print("mean = ", np.mean(nums).round(2))
print("median = ", np.median(nums).round(2))
print("var = ", np.var(nums).round(2))
print("std = ", np.std(nums).round(2))

min =  0.0
max =  3.83
sum =  30.66
mean =  1.92
median =  1.92
var =  1.39
std =  1.18


## Random

In [108]:
flip = np.random.choice([0,1], 10)
flip

array([0, 0, 1, 1, 0, 1, 0, 0, 0, 1])

In [109]:
np.random.rand(10,20,9)

array([[[0.37186052, 0.98496475, 0.92300328, ..., 0.1648018 ,
         0.49165877, 0.46722098],
        [0.29949287, 0.5567671 , 0.68556894, ..., 0.56964676,
         0.06774306, 0.404917  ],
        [0.60877984, 0.03833931, 0.20211719, ..., 0.36804242,
         0.83601037, 0.98503129],
        ...,
        [0.96298467, 0.82057372, 0.22511696, ..., 0.31185522,
         0.14362197, 0.29906797],
        [0.92451487, 0.72121631, 0.09174731, ..., 0.24396957,
         0.41613081, 0.67238205],
        [0.21238818, 0.27008505, 0.29417281, ..., 0.49227117,
         0.94354087, 0.94914917]],

       [[0.407747  , 0.22428368, 0.36067887, ..., 0.42147369,
         0.24767892, 0.51699229],
        [0.36235488, 0.18002083, 0.12335265, ..., 0.9619619 ,
         0.30104495, 0.10543487],
        [0.11743311, 0.12211584, 0.35046007, ..., 0.40549588,
         0.95768784, 0.73098994],
        ...,
        [0.76095118, 0.04349266, 0.70717339, ..., 0.84349868,
         0.41460224, 0.57651199],
        [0.3

In [110]:
mu, sigma = 0, 0.1 # mean and standard deviation
s = np.random.normal(mu, sigma, 1000)

In [111]:
s

array([ 1.70999546e-01,  3.39738659e-02,  7.62902700e-03,  5.92210092e-02,
       -1.05033731e-01,  2.00406285e-02, -2.19349097e-02, -9.59504619e-02,
        3.50784491e-02,  2.61021084e-02, -3.90688055e-02,  1.27701322e-01,
       -1.71071385e-02, -1.27296519e-01, -1.10626769e-01,  5.18758068e-02,
       -7.67583407e-03,  1.10957202e-01,  1.18922072e-01,  4.86885282e-02,
        2.66243166e-02, -1.67725613e-02, -1.95802733e-02,  1.24433128e-02,
        1.35550680e-01, -1.76107860e-01,  3.03624892e-02, -1.31742716e-03,
       -5.56592379e-03, -6.07877444e-02,  8.45027169e-02, -1.20632590e-02,
       -1.76687286e-01, -9.70827940e-03,  1.24240274e-01, -1.60497409e-01,
       -9.76969151e-02,  8.95471112e-02,  9.66913212e-04,  2.14385320e-01,
        8.04818004e-02,  1.36422010e-01, -2.67942885e-01,  2.72293002e-01,
        6.84045007e-02, -4.02445475e-02,  4.40734538e-02, -1.45630859e-01,
        8.44656398e-02, -2.55511886e-01, -2.32735437e-01,  1.09743297e-01,
       -1.17763657e-01,  

### Exercise
* Simulate a six-sided dice using numpy.random.choice(), generate a list of values you would obtain from 10 throws.
* Simulate a two-sided coin toss that is NOT fair: it is twice as likely to have head than tails.

In [112]:
np.random.choice([1,2,3,4,5,6],10)


array([5, 2, 6, 6, 1, 2, 5, 4, 2, 4])

In [113]:
np.random.choice(["H","H","T"],10)


array(['T', 'H', 'H', 'H', 'T', 'H', 'T', 'T', 'T', 'H'], dtype='<U1')